require:
  - rubocop-rubycw

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true

Rubycw/Rubycw:
  Enabled: true
  Exclude:
    - 'test/**/*_test.rb'

Lint/DuplicateMethods:
  Enabled: true
  Include:
    - 'test/**/*_test.rb'
